#SERVER SETUP
server:
  port: 8080


#DATABASE SETUP
spring:
  application:
    name: GHARBHADA
  datasource:
        url: jdbc:mysql://localhost:3306/gharbhada
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver

#HIBERNATE CONFIGURATION
  jpa:
        properties:
            hibenate:
               dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate.ddl-auto: update
        show-sql: true    

#Image size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
         
#Image Setup
project:
         image: images/ 
  
 
         
 
springfox:
  documentation:
    swagger-ui:
      enabled: true 

        